version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - webnet

  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:
