version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - webnet

  frontend:
    build: .
    ports:
      - "2239:80"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:

    nginx:
    image: nginx:alpine
    container_name: nginx-suarez
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

