version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - webnet

  frontend:
    build: .
    # No mapees puertos aquí, porque el nginx hará de proxy y servirá el frontend
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx-suarez
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - webnet

networks:
  webnet:
