version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - webnet

  frontend:
    build: .
    networks:
      - webnet

nginx:
  image: nginx:alpine
  container_name: nginx-suarez
  ports:
    - "2330:80"     # Cambiar puerto externo 80 por 2330
    - "8443:443"    # HTTPS puede mantenerse, si no está en uso
  depends_on:
      - backend
      - frontend
  volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
  networks:
      - webnet

networks:
  webnet:
