version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - webnet

  frontend:
    build: .

    env_file:
      - .env
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx-suarez
    ports:
      - "2330:2330"      # HTTP estándar (puedes cambiar si quieres)
      - "443:8443"   # HTTPS (mapear 443 externo a 8443 interno)
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./dist:/usr/share/nginx/html:ro   
    networks:
      - webnet

networks:
  webnet:
