version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - webnet

  frontend:
    build: .
    ports:
      - "2239:3000"
    env_file:
      - .env
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx-suarez
    ports:
      - "2334:2334"  # HTTP personalizado
      - "8443:8443"  # HTTPS estándar
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - webnet

networks:
  webnet:
